# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LOCAL_PATH := vendor/mattel/nabise

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/bin/6620_launcher:bin/6620_launcher \
    $(LOCAL_PATH)/proprietary/bin/6620_wmt_concurrency:bin/6620_wmt_concurrency \
    $(LOCAL_PATH)/proprietary/bin/6620_wmt_lpbk:bin/6620_wmt_lpbk \
    $(LOCAL_PATH)/proprietary/bin/MtkCodecService:bin/MtkCodecService \
    $(LOCAL_PATH)/proprietary/bin/akmd09911:bin/akmd09911 \
    $(LOCAL_PATH)/proprietary/bin/akmd8963:bin/akmd8963 \
    $(LOCAL_PATH)/proprietary/bin/audiocmdservice_atci:bin/audiocmdservice_atci \
    $(LOCAL_PATH)/proprietary/bin/guiext-server:bin/guiext-server \
    $(LOCAL_PATH)/proprietary/bin/msensord:bin/msensord \
    $(LOCAL_PATH)/proprietary/bin/nvram_agent_binder:bin/nvram_agent_binder \
    $(LOCAL_PATH)/proprietary/bin/nvram_daemon:bin/nvram_daemon \
    $(LOCAL_PATH)/proprietary/bin/pq:bin/pq \
    $(LOCAL_PATH)/proprietary/bin/wmt_loader:bin/wmt_loader \
    $(LOCAL_PATH)/proprietary/etc/bluetooth/auto_pair_blacklist.conf:etc/bluetooth/auto_pair_blacklist.conf \
    $(LOCAL_PATH)/proprietary/etc/bluetooth/auto_pair_devlist.conf:etc/bluetooth/auto_pair_devlist.conf \
    $(LOCAL_PATH)/proprietary/etc/bluetooth/bt_stack.conf:etc/bluetooth/bt_stack.conf \
    $(LOCAL_PATH)/proprietary/etc/clatd.conf:etc/clatd.conf \
    $(LOCAL_PATH)/proprietary/etc/custom.conf:etc/custom.conf \
    $(LOCAL_PATH)/proprietary/etc/dhcpcd/dhcpcd-hooks/20-dns.conf:etc/dhcpcd/dhcpcd-hooks/20-dns.conf \
    $(LOCAL_PATH)/proprietary/etc/dhcpcd/dhcpcd-hooks/95-configured:etc/dhcpcd/dhcpcd-hooks/95-configured \
    $(LOCAL_PATH)/proprietary/etc/dhcpcd/dhcpcd-run-hooks:etc/dhcpcd/dhcpcd-run-hooks \
    $(LOCAL_PATH)/proprietary/lib/egl/egl.cfg:lib/egl/egl.cfg \
    $(LOCAL_PATH)/proprietary/etc/factory.ini:etc/factory.ini \
    $(LOCAL_PATH)/proprietary/etc/firmware/ROMv2_patch_1_0_hdr.bin:etc/firmware/ROMv2_patch_1_0_hdr.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/ROMv2_patch_1_1_hdr.bin:etc/firmware/ROMv2_patch_1_1_hdr.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/S_ANDRO_SFL.ini:etc/firmware/S_ANDRO_SFL.ini \
    $(LOCAL_PATH)/proprietary/etc/firmware/WIFI_RAM_CODE_8127:etc/firmware/WIFI_RAM_CODE_8127 \
    $(LOCAL_PATH)/proprietary/etc/firmware/WMT_SOC.cfg:etc/firmware/WMT_SOC.cfg \
    $(LOCAL_PATH)/proprietary/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin:etc/firmware/mt6627/mt6627_fm_v1_coeff.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/mt6627/mt6627_fm_v1_patch.bin:etc/firmware/mt6627/mt6627_fm_v1_patch.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin:etc/firmware/mt6627/mt6627_fm_v2_coeff.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/mt6627/mt6627_fm_v2_patch.bin:etc/firmware/mt6627/mt6627_fm_v2_patch.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin:etc/firmware/mt6627/mt6627_fm_v3_coeff.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/mt6627/mt6627_fm_v3_patch.bin:etc/firmware/mt6627/mt6627_fm_v3_patch.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin:etc/firmware/mt6627/mt6627_fm_v4_coeff.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/mt6627/mt6627_fm_v4_patch.bin:etc/firmware/mt6627/mt6627_fm_v4_patch.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin:etc/firmware/mt6627/mt6627_fm_v5_coeff.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/mt6627/mt6627_fm_v5_patch.bin:etc/firmware/mt6627/mt6627_fm_v5_patch.bin \
    $(LOCAL_PATH)/proprietary/etc/fmr/mt6627_fm_cust.cfg:etc/fmr/mt6627_fm_cust.cfg \
    $(LOCAL_PATH)/proprietary/etc/mtklog-config.prop:etc/mtklog-config.prop \
    $(LOCAL_PATH)/proprietary/etc/wide-dhcpv6/dhcp6c.conf:etc/wide-dhcpv6/dhcp6c.conf \
    $(LOCAL_PATH)/proprietary/etc/wide-dhcpv6/dhcp6c.script:etc/wide-dhcpv6/dhcp6c.script \
    $(LOCAL_PATH)/proprietary/etc/wide-dhcpv6/dhcp6cDNS.conf:etc/wide-dhcpv6/dhcp6cDNS.conf \
    $(LOCAL_PATH)/proprietary/etc/wide-dhcpv6/dhcp6cctlkey:etc/wide-dhcpv6/dhcp6cctlkey \
    $(LOCAL_PATH)/proprietary/etc/wide-dhcpv6/dhcp6s.conf:etc/wide-dhcpv6/dhcp6s.conf \
    $(LOCAL_PATH)/proprietary/lib/egl/libEGL_mali.so:lib/egl/libEGL_mali.so \
    $(LOCAL_PATH)/proprietary/lib/egl/libGLESv1_CM_mali.so:lib/egl/libGLESv1_CM_mali.so \
    $(LOCAL_PATH)/proprietary/lib/egl/libGLESv2_mali.so:lib/egl/libGLESv2_mali.so \
    $(LOCAL_PATH)/proprietary/lib/hw/audio.primary.mt8127.so:lib/hw/audio.primary.mt8127.so \
    $(LOCAL_PATH)/proprietary/lib/hw/camera.mt8127.so:lib/hw/camera.mt8127.so \
    $(LOCAL_PATH)/proprietary/lib/hw/gps.default.so:lib/hw/gps.default.so \
    $(LOCAL_PATH)/proprietary/lib/hw/gralloc.mt8127.so:lib/hw/gralloc.mt8127.so \
    $(LOCAL_PATH)/proprietary/lib/hw/hwcomposer.mt8127.so:lib/hw/hwcomposer.mt8127.so \
    $(LOCAL_PATH)/proprietary/lib/hw/sensors.mt8127.so:lib/hw/sensors.mt8127.so \
    $(LOCAL_PATH)/proprietary/lib/lib3a.so:lib/lib3a.so \
    $(LOCAL_PATH)/proprietary/lib/libBnMtkCodec.so:lib/libBnMtkCodec.so \
    $(LOCAL_PATH)/proprietary/lib/libGdmaScalerPipe.so:lib/libGdmaScalerPipe.so \
    $(LOCAL_PATH)/proprietary/lib/libJpgDecPipe.so:lib/libJpgDecPipe.so \
    $(LOCAL_PATH)/proprietary/lib/libJpgEncPipe.so:lib/libJpgEncPipe.so \
    $(LOCAL_PATH)/proprietary/lib/libMali.so:lib/libMali.so \
    $(LOCAL_PATH)/proprietary/lib/libSwJpgCodec.so:lib/libSwJpgCodec.so \
    $(LOCAL_PATH)/proprietary/lib/lib_uree_mtk_crypto.so:lib/lib_uree_mtk_crypto.so \
    $(LOCAL_PATH)/proprietary/lib/lib_uree_mtk_video_secure_al.so:lib/lib_uree_mtk_video_secure_al.so \
    $(LOCAL_PATH)/proprietary/lib/libaed.so:lib/libaed.so \
    $(LOCAL_PATH)/proprietary/lib/libaudio-resampler.so:lib/libaudio-resampler.so \
    $(LOCAL_PATH)/proprietary/lib/libaudiocompensationfilter.so:lib/libaudiocompensationfilter.so \
    $(LOCAL_PATH)/proprietary/lib/libaudiocomponentengine.so:lib/libaudiocomponentengine.so \
    $(LOCAL_PATH)/proprietary/lib/libaudiocustparam.so:lib/libaudiocustparam.so \
    $(LOCAL_PATH)/proprietary/lib/libaudiodcrflt.so:lib/libaudiodcrflt.so \
    $(LOCAL_PATH)/proprietary/lib/libaudiomtkdcremoval.so:lib/libaudiomtkdcremoval.so \
    $(LOCAL_PATH)/proprietary/lib/libaudiosetting.so:lib/libaudiosetting.so \
    $(LOCAL_PATH)/proprietary/lib/libbessound_hd_mtk.so:lib/libbessound_hd_mtk.so \
    $(LOCAL_PATH)/proprietary/lib/libblisrc.so:lib/libblisrc.so \
    $(LOCAL_PATH)/proprietary/lib/libblisrc32.so:lib/libblisrc32.so \
    $(LOCAL_PATH)/proprietary/lib/libbluetooth_mtk.so:lib/libbluetooth_mtk.so \
    $(LOCAL_PATH)/proprietary/lib/libbluetooth_relayer.so:lib/libbluetooth_relayer.so \
    $(LOCAL_PATH)/proprietary/lib/libbluetoothdrv.so:lib/libbluetoothdrv.so \
    $(LOCAL_PATH)/proprietary/lib/libbluetoothem_mtk.so:lib/libbluetoothem_mtk.so \
    $(LOCAL_PATH)/proprietary/lib/libbwc.so:lib/libbwc.so \
    $(LOCAL_PATH)/proprietary/lib/libcam.camadapter.so:lib/libcam.camadapter.so \
    $(LOCAL_PATH)/proprietary/lib/libcam.campipe.so:lib/libcam.campipe.so \
    $(LOCAL_PATH)/proprietary/lib/libcam.camshot.so:lib/libcam.camshot.so \
    $(LOCAL_PATH)/proprietary/lib/libcam.client.so:lib/libcam.client.so \
    $(LOCAL_PATH)/proprietary/lib/libcam.device1.so:lib/libcam.device1.so \
    $(LOCAL_PATH)/proprietary/lib/libcam.exif.so:lib/libcam.exif.so \
    $(LOCAL_PATH)/proprietary/lib/libcam.paramsmgr.so:lib/libcam.paramsmgr.so \
    $(LOCAL_PATH)/proprietary/lib/libcam.utils.sensorlistener.so:lib/libcam.utils.sensorlistener.so \
    $(LOCAL_PATH)/proprietary/lib/libcam.utils.so:lib/libcam.utils.so \
    $(LOCAL_PATH)/proprietary/lib/libcam_hwutils.so:lib/libcam_hwutils.so \
    $(LOCAL_PATH)/proprietary/lib/libcam_mmp.so:lib/libcam_mmp.so \
    $(LOCAL_PATH)/proprietary/lib/libcam_platform.so:lib/libcam_platform.so \
    $(LOCAL_PATH)/proprietary/lib/libcam_utils.so:lib/libcam_utils.so \
    $(LOCAL_PATH)/proprietary/lib/libcamalgo.so:lib/libcamalgo.so \
    $(LOCAL_PATH)/proprietary/lib/libcamdrv.so:lib/libcamdrv.so \
    $(LOCAL_PATH)/proprietary/lib/libcamera_client_mtk.so:lib/libcamera_client_mtk.so \
    $(LOCAL_PATH)/proprietary/lib/libcameraanalyzer.so:lib/libcameraanalyzer.so \
    $(LOCAL_PATH)/proprietary/lib/libcameracustom.so:lib/libcameracustom.so \
    $(LOCAL_PATH)/proprietary/lib/libcustom_nvram.so:lib/libcustom_nvram.so \
    $(LOCAL_PATH)/proprietary/lib/libcvsd_mtk.so:lib/libcvsd_mtk.so \
    $(LOCAL_PATH)/proprietary/lib/libdpframework.so:lib/libdpframework.so \
    $(LOCAL_PATH)/proprietary/lib/libdrmmtkutil.so:lib/libdrmmtkutil.so \
    $(LOCAL_PATH)/proprietary/lib/libdrmmtkwhitelist.so:lib/libdrmmtkwhitelist.so \
    $(LOCAL_PATH)/proprietary/lib/libem_support_jni.so:lib/libem_support_jni.so \
    $(LOCAL_PATH)/proprietary/lib/libfeatureio.so:lib/libfeatureio.so \
    $(LOCAL_PATH)/proprietary/lib/libfile_op.so:lib/libfile_op.so \
    $(LOCAL_PATH)/proprietary/lib/libfmjni.so:lib/libfmjni.so \
    $(LOCAL_PATH)/proprietary/lib/libgralloc_extra.so:lib/libgralloc_extra.so \
    $(LOCAL_PATH)/proprietary/lib/libgui_ext.so:lib/libgui_ext.so \
    $(LOCAL_PATH)/proprietary/lib/libhwm.so:lib/libhwm.so \
    $(LOCAL_PATH)/proprietary/lib/libimageio.so:lib/libimageio.so \
    $(LOCAL_PATH)/proprietary/lib/libimageio_plat_drv.so:lib/libimageio_plat_drv.so \
    $(LOCAL_PATH)/proprietary/lib/libion.so:lib/libion.so \
    $(LOCAL_PATH)/proprietary/lib/libion_mtk.so:lib/libion_mtk.so \
    $(LOCAL_PATH)/proprietary/lib/libm4u.so:lib/libm4u.so \
    $(LOCAL_PATH)/proprietary/lib/libmatv_cust.so:lib/libmatv_cust.so \
    $(LOCAL_PATH)/proprietary/lib/libmemtrack.so:lib/libmemtrack.so \
    $(LOCAL_PATH)/proprietary/lib/libmhalImageCodec.so:lib/libmhalImageCodec.so \
    $(LOCAL_PATH)/proprietary/lib/libmmprofile.so:lib/libmmprofile.so \
    $(LOCAL_PATH)/proprietary/lib/libmnl.so:lib/libmnl.so \
    $(LOCAL_PATH)/proprietary/lib/libmpo.so:lib/libmpo.so \
    $(LOCAL_PATH)/proprietary/lib/libmpodecoder.so:lib/libmpodecoder.so \
    $(LOCAL_PATH)/proprietary/lib/libmpoencoder.so:lib/libmpoencoder.so \
    $(LOCAL_PATH)/proprietary/lib/libmsbc_mtk.so:lib/libmsbc_mtk.so \
    $(LOCAL_PATH)/proprietary/lib/libmtcloader.so:lib/libmtcloader.so \
    $(LOCAL_PATH)/proprietary/lib/libmtk_drvb.so:lib/libmtk_drvb.so \
    $(LOCAL_PATH)/proprietary/lib/libmtk_mali_user.so:lib/libmtk_mali_user.so \
    $(LOCAL_PATH)/proprietary/lib/libmtk_mmutils.so:lib/libmtk_mmutils.so \
    $(LOCAL_PATH)/proprietary/lib/libmtkjpeg.so:lib/libmtkjpeg.so \
    $(LOCAL_PATH)/proprietary/lib/libmtklimiter.so:lib/libmtklimiter.so \
    $(LOCAL_PATH)/proprietary/lib/libmtkplayer.so:lib/libmtkplayer.so \
    $(LOCAL_PATH)/proprietary/lib/libmtkshifter.so:lib/libmtkshifter.so \
    $(LOCAL_PATH)/proprietary/lib/libnvram.so:lib/libnvram.so \
    $(LOCAL_PATH)/proprietary/lib/libnvram_daemon_callback.so:lib/libnvram_daemon_callback.so \
    $(LOCAL_PATH)/proprietary/lib/libnvram_platform.so:lib/libnvram_platform.so \
    $(LOCAL_PATH)/proprietary/lib/libnvram_sec.so:lib/libnvram_sec.so \
    $(LOCAL_PATH)/proprietary/lib/libnvramagentclient.so:lib/libnvramagentclient.so \
    $(LOCAL_PATH)/proprietary/lib/libperfservicenative.so:lib/libperfservicenative.so \
    $(LOCAL_PATH)/proprietary/lib/libshowlogo.so:lib/libshowlogo.so \
    $(LOCAL_PATH)/proprietary/lib/libspeech_enh_lib.so:lib/libspeech_enh_lib.so \
    $(LOCAL_PATH)/proprietary/lib/libstagefright_memutil.so:lib/libstagefright_memutil.so \
    $(LOCAL_PATH)/proprietary/lib/libstagefrighthw.so:lib/libstagefrighthw.so \
    $(LOCAL_PATH)/proprietary/lib/libtz_uree.so:lib/libtz_uree.so \
    $(LOCAL_PATH)/proprietary/lib/libui_ext.so:lib/libui_ext.so \
    $(LOCAL_PATH)/proprietary/lib/liburee_meta_drmkeyinstall_v2.so:lib/liburee_meta_drmkeyinstall_v2.so \
    $(LOCAL_PATH)/proprietary/lib/libvcodec_utility.so:lib/libvcodec_utility.so \
    $(LOCAL_PATH)/proprietary/vendor/media/LMspeed_508.emd:vendor/media/LMspeed_508.emd \
    $(LOCAL_PATH)/proprietary/vendor/media/PFFprec_600.emd:vendor/media/PFFprec_600.emd \
    $(LOCAL_PATH)/proprietary/xbin/mnld:xbin/mnld \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwvdrm_L3.so:vendor/lib/libwvdrm_L3.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:vendor/lib/libWVStreamControlAPI_L3.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:vendor/lib/mediadrm/libwvdrmengine.so \
    $(LOCAL_PATH)/proprietary/etc/mtk_omx_core.cfg:etc/mtk_omx_core.cfg \
    $(LOCAL_PATH)/proprietary/lib/libMtkOmxCore.so:lib/libMtkOmxCore.so \
    $(LOCAL_PATH)/proprietary/lib/libClearMotionFW.so:lib/libClearMotionFW.so \
    $(LOCAL_PATH)/proprietary/lib/libMtkOmxVdecEx.so:lib/libMtkOmxVdecEx.so \
    $(LOCAL_PATH)/proprietary/lib/libMtkOmxVenc.so:lib/libMtkOmxVenc.so \
    $(LOCAL_PATH)/proprietary/lib/libHEVCdec_sa.ca7.android.so:lib/libHEVCdec_sa.ca7.android.so \
    $(LOCAL_PATH)/proprietary/lib/libvc1dec_sa.ca7.so:lib/libvc1dec_sa.ca7.so \
    $(LOCAL_PATH)/proprietary/lib/libvcodec_oal.so:lib/libvcodec_oal.so \
    $(LOCAL_PATH)/proprietary/lib/libvcodecdrv.so:lib/libvcodecdrv.so \
    $(LOCAL_PATH)/proprietary/lib/librrc.so:lib/librrc.so \
    $(LOCAL_PATH)/proprietary/lib/libvp8dec_sa.ca7.so:lib/libvp8dec_sa.ca7.so \
    $(LOCAL_PATH)/proprietary/lib/libvp8enc_sa.ca7.so:lib/libvp8enc_sa.ca7.so \
    $(LOCAL_PATH)/proprietary/lib/libvp9dec_sa.ca7.so:lib/libvp9dec_sa.ca7.so \
    $(LOCAL_PATH)/proprietary/lib/libh264enc_sa.ca7.so:lib/libh264enc_sa.ca7.so \
    $(LOCAL_PATH)/proprietary/lib/libh264enc_sb.ca7.so:lib/libh264enc_sb.ca7.so \
    $(LOCAL_PATH)/proprietary/lib/libmp4enc_sa.ca7.so:lib/libmp4enc_sa.ca7.so \
    $(LOCAL_PATH)/proprietary/lib/libmp4enc_xa.ca7.so:lib/libmp4enc_xa.ca7.so
